"""Export forged teams as runnable LangGraph StateGraph Python modules."""

from __future__ import annotations

import re
import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentforge.composition.models import ForgedTeam


def _to_python_id(name: str) -> str:
    """Convert an agent name like 'Code Architect' to a valid Python identifier."""
    slug = re.sub(r"[^a-zA-Z0-9]", "_", name.lower())
    slug = re.sub(r"_+", "_", slug).strip("_")
    if slug and slug[0].isdigit():
        slug = f"agent_{slug}"
    return slug or "agent"


def _indent(text: str, prefix: str = "    ") -> str:
    return textwrap.indent(text, prefix)


class LangGraphExporter:
    """Generate a runnable LangGraph Python module from a ForgedTeam."""

    def export(self, team: ForgedTeam) -> str:
        """Return a complete Python module string defining a LangGraph StateGraph."""
        agents = []
        for ft in team.teammates:
            agents.append({
                "name": ft.teammate.name,
                "py_id": _to_python_id(ft.teammate.name),
                "archetype": ft.teammate.archetype,
                "skill_md": ft.skill_folder.skill_md,
                "skill_name": ft.skill_folder.skill_name,
            })

        sections = [
            self._render_header(team),
            self._render_imports(),
            self._render_state(),
            self._render_agent_nodes(agents),
            self._render_router(team.conductor.routing_table, agents),
            self._render_workflow_nodes(team),
            self._render_build_graph(agents, team),
            self._render_main(),
        ]
        return "\n\n".join(sections) + "\n"

    def _render_header(self, team: ForgedTeam) -> str:
        n = len(team.teammates)
        return (
            f'"""{team.role_title} — LangGraph Agent Team\n'
            f"\n"
            f"Auto-generated by AgentForge from a forged team.\n"
            f"Defines a {n}-agent team with conductor routing.\n"
            f"\n"
            f"Usage:\n"
            f"    python {_to_python_id(team.role_title)}_graph.py\n"
            f"\n"
            f'Requires: pip install "agentforge[langgraph]"\n'
            f'"""\n'
        )

    def _render_imports(self) -> str:
        return textwrap.dedent("""\
            from __future__ import annotations

            import operator
            from typing import Annotated, Any, TypedDict

            from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
            from langgraph.graph import END, StateGraph
        """).rstrip()

    def _render_state(self) -> str:
        return textwrap.dedent("""\
            # ---------------------------------------------------------------------------
            # State
            # ---------------------------------------------------------------------------

            class TeamState(TypedDict):
                \"\"\"Shared state threaded through the graph.\"\"\"
                messages: Annotated[list, operator.add]
                current_agent: str
                task: str
                result: str
                metadata: dict[str, Any]
        """).rstrip()

    def _render_agent_nodes(self, agents: list[dict]) -> str:
        lines = [
            "# ---------------------------------------------------------------------------",
            "# Agent node factories",
            "# ---------------------------------------------------------------------------",
            "",
            "AGENT_SKILLS: dict[str, str] = {",
        ]
        for a in agents:
            escaped = a["skill_md"].replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
            lines.append(f'    "{a["py_id"]}": """{escaped}""",')
        lines.append("}")
        lines.append("")
        lines.append("")
        lines.append(textwrap.dedent("""\
            def make_agent_node(agent_id: str):
                \"\"\"Create a node function that invokes the LLM with this agent's skill.\"\"\"
                skill_prompt = AGENT_SKILLS[agent_id]

                def node(state: TeamState) -> dict:
                    # Replace this with your preferred LLM client.
                    # The skill_prompt contains the full SKILL.md for context.
                    from langchain_anthropic import ChatAnthropic

                    llm = ChatAnthropic(model="claude-sonnet-4-20250514")
                    response = llm.invoke([
                        SystemMessage(content=skill_prompt),
                        HumanMessage(content=state["task"]),
                    ])
                    return {
                        "messages": [AIMessage(content=response.content, name=agent_id)],
                        "result": response.content,
                        "current_agent": agent_id,
                    }

                node.__name__ = agent_id
                return node""").rstrip())
        return "\n".join(lines)

    def _render_router(
        self, routing_table: dict[str, list[str]], agents: list[dict]
    ) -> str:
        lines = [
            "# ---------------------------------------------------------------------------",
            "# Conductor router",
            "# ---------------------------------------------------------------------------",
            "",
            "ROUTING_TABLE: dict[str, list[str]] = {",
        ]
        name_to_id = {a["name"]: a["py_id"] for a in agents}
        for agent_name, keywords in routing_table.items():
            py_id = name_to_id.get(agent_name, _to_python_id(agent_name))
            kw_repr = repr(keywords)
            lines.append(f'    "{py_id}": {kw_repr},')
        lines.append("}")
        lines.append("")
        lines.append("")

        # Build the default agent id
        default_id = agents[0]["py_id"] if agents else '"unknown"'

        lines.append(textwrap.dedent(f"""\
            def route_task(state: TeamState) -> str:
                \"\"\"Route a task to the best agent based on keyword matching.\"\"\"
                task_lower = state["task"].lower()
                scores: dict[str, int] = {{}}
                for agent_id, keywords in ROUTING_TABLE.items():
                    scores[agent_id] = sum(1 for kw in keywords if kw in task_lower)

                best = max(scores, key=scores.get)  # type: ignore[arg-type]
                if scores[best] > 0:
                    return best
                # Fallback to first agent
                return "{default_id}"
        """).rstrip())
        return "\n".join(lines)

    def _render_workflow_nodes(self, team: ForgedTeam) -> str:
        if not team.conductor.workflows:
            return (
                "# ---------------------------------------------------------------------------\n"
                "# Workflows\n"
                "# ---------------------------------------------------------------------------\n"
                "\n"
                "# No multi-agent workflows were generated for this team."
            )

        lines = [
            "# ---------------------------------------------------------------------------",
            "# Workflows",
            "# ---------------------------------------------------------------------------",
            "",
            "WORKFLOWS = [",
        ]
        for wf in team.conductor.workflows:
            lines.append("    {")
            lines.append(f'        "name": {wf.name!r},')
            lines.append(f'        "trigger": {wf.trigger!r},')
            lines.append(f'        "steps": [')
            for step in wf.steps:
                py_id = _to_python_id(step.agent)
                lines.append(f'            {{"agent": "{py_id}", "task": {step.task!r}}},')
            lines.append("        ],")
            lines.append("    },")
        lines.append("]")
        return "\n".join(lines)

    def _render_build_graph(self, agents: list[dict], team: ForgedTeam) -> str:
        lines = [
            "# ---------------------------------------------------------------------------",
            "# Graph construction",
            "# ---------------------------------------------------------------------------",
            "",
            "",
            "def build_graph() -> StateGraph:",
            '    """Build the LangGraph StateGraph for this agent team."""',
            "    graph = StateGraph(TeamState)",
            "",
            "    # Add agent nodes",
        ]
        for a in agents:
            lines.append(f'    graph.add_node("{a["py_id"]}", make_agent_node("{a["py_id"]}"))')

        lines.append("")
        lines.append("    # Conductor routing — entry point")
        lines.append("    graph.set_conditional_entry_point(route_task)")
        lines.append("")
        lines.append("    # Each agent node terminates after producing a result")
        for a in agents:
            lines.append(f'    graph.add_edge("{a["py_id"]}", END)')

        lines.append("")
        lines.append("    return graph")
        lines.append("")
        lines.append("")
        lines.append("# Compile the graph for execution")
        lines.append("graph = build_graph()")
        lines.append("app = graph.compile()")
        return "\n".join(lines)

    def _render_main(self) -> str:
        return textwrap.dedent("""\
            # ---------------------------------------------------------------------------
            # CLI entry point
            # ---------------------------------------------------------------------------


            if __name__ == "__main__":
                import sys

                task = " ".join(sys.argv[1:]) or "Hello, what can you help me with?"
                result = app.invoke({
                    "messages": [],
                    "current_agent": "",
                    "task": task,
                    "result": "",
                    "metadata": {},
                })
                print(f"\\nRouted to: {result['current_agent']}")
                print(f"\\nResult:\\n{result['result']}")
        """).rstrip()
