"""Cron agent template generation.

Generates cron-appropriate scaffolding for scheduled/autonomous agents:
  - Context isolation guardrails (fresh context per run)
  - Delivery-formatted output templates
  - Schedule configuration block
  - Failure/retry handling scaffold
"""

from __future__ import annotations

from typing import Any

from agentforge.models.extracted_skills import (
    ExtractionResult,
    MethodologyExtraction,
)


class CronConfig:
    """Configuration container for cron agent settings."""

    def __init__(
        self,
        schedule: str = "0 8 * * *",
        timezone: str = "UTC",
        max_retries: int = 3,
        retry_delay_seconds: int = 60,
        timeout_seconds: int = 300,
        delivery_format: str = "markdown",
        context_isolation: bool = True,
    ):
        self.schedule = schedule
        self.timezone = timezone
        self.max_retries = max_retries
        self.retry_delay_seconds = retry_delay_seconds
        self.timeout_seconds = timeout_seconds
        self.delivery_format = delivery_format
        self.context_isolation = context_isolation

    def to_dict(self) -> dict[str, Any]:
        return {
            "schedule": self.schedule,
            "timezone": self.timezone,
            "max_retries": self.max_retries,
            "retry_delay_seconds": self.retry_delay_seconds,
            "timeout_seconds": self.timeout_seconds,
            "delivery_format": self.delivery_format,
            "context_isolation": self.context_isolation,
        }


class CronTemplateGenerator:
    """Generates cron-specific scaffolding for scheduled agents."""

    def generate_cron_yaml_block(self, config: CronConfig) -> str:
        """Generate the cron_config: YAML block for identity YAML."""
        import yaml
        return yaml.dump(
            {"cron_config": config.to_dict()},
            default_flow_style=False,
            sort_keys=False,
        )

    def generate_guardrails(self) -> str:
        """Generate context isolation guardrails for cron agents."""
        return """## Context Isolation

This agent runs on a schedule. Each execution starts with a fresh context.

### Rules
- Do NOT reference previous runs or conversation history
- Do NOT assume any state carries over between executions
- Start each run by gathering fresh data from configured sources
- End each run with a complete, self-contained deliverable
- If a required data source is unavailable, report the failure clearly
"""

    def generate_delivery_template(
        self,
        extraction: ExtractionResult,
        config: CronConfig,
    ) -> str:
        """Generate delivery-formatted output template for cron output."""
        title = extraction.role.title
        lines = [
            f"# {title} — Scheduled Report",
            "",
            "## Delivery Template",
            "",
            "Each scheduled run should produce output in this format:",
            "",
            "```",
            f"# {title} Report — {{date}}",
            "",
            "## Summary",
            "{{executive_summary}}",
            "",
            "## Key Findings",
            "{{findings}}",
            "",
            "## Action Items",
            "{{action_items}}",
            "",
            "## Data Sources",
            "{{sources_consulted}}",
            "",
            f"---",
            f"*Generated by {title} | Schedule: {config.schedule} {config.timezone}*",
            "```",
            "",
        ]
        return "\n".join(lines)

    def generate_failure_handler(self, config: CronConfig) -> str:
        """Generate failure/retry handling scaffold."""
        return f"""## Failure Handling

### Retry Policy
- Max retries: {config.max_retries}
- Delay between retries: {config.retry_delay_seconds}s
- Timeout per run: {config.timeout_seconds}s

### On Failure
1. Log the error with timestamp and context
2. If retries remain, wait and retry with fresh context
3. If all retries exhausted, produce a failure report:

```
# FAILED: {{agent_name}} — {{date}}

## Error
{{error_description}}

## Attempted
{{what_was_tried}}

## Recommendation
{{suggested_fix}}
```
"""

    def enrich_identity_yaml(
        self,
        identity_yaml: str,
        config: CronConfig,
    ) -> str:
        """Append cron_config block to existing identity YAML."""
        cron_block = self.generate_cron_yaml_block(config)
        return identity_yaml.rstrip() + "\n\n" + cron_block

    def enrich_skill_md(
        self,
        skill_md: str,
        extraction: ExtractionResult,
        config: CronConfig,
    ) -> str:
        """Prepend cron guardrails and delivery template to skill content."""
        guardrails = self.generate_guardrails()
        delivery = self.generate_delivery_template(extraction, config)
        failure = self.generate_failure_handler(config)

        # Insert after the frontmatter
        parts = skill_md.split("---", 2)
        if len(parts) >= 3:
            # parts[0] is empty, parts[1] is frontmatter, parts[2] is body
            return (
                "---"
                + parts[1]
                + "---\n\n"
                + guardrails
                + "\n"
                + delivery
                + "\n"
                + failure
                + "\n"
                + parts[2]
            )
        # Fallback: prepend to entire content
        return guardrails + "\n" + delivery + "\n" + failure + "\n" + skill_md
